### ISSUE TITLE
Publish release with `extra` feature

### ISSUE THREAD

**Issue by mitchhentges** [tschaub/gulp-newer#37]
For setting `gulp-newer` up with `sass`, I want sass to invoke the root file, but I want to check `gulp-newer` against all source files.

This feature is added in the `extra` flag, which isn't released yet. Can it be released?
Btw, thanks tschaub for this sick incremental build tool, and TimMensch for implementing this sick feature :)

**Comment by tschaub** [comment]
Thanks for the tests @mitchhentges.  Just published `gulp-newer@1.2` with `extra` support.
