### ISSUE TITLE
Doubt on the approach

### ISSUE THREAD

**Issue by tomasdev** [tschaub/gulp-newer#4]
Hi @tschaub I found asking myself why is `gulp-newer` and `gulp-changed` having the same approach, with a dependency on the destination directory?

That drops the support for pipes that use `gulp-rename` for example, and I bet the modified source files are the ones that matter the most.

If source wasn't modified and the task is executed, destination doesn't really matter, does it? Am I missing something?

**Comment by KevinBatdorf** [comment]
I'm trying to accomplish something similar to the OP. My file structure looks like this, as an example:
```bash
public/
↳css/
  ↳styles.css
  ↳admin.css
  ↳min/
    ↳styles.min.css
    ↳mstyles.min.css.map
↳src/
  ↳scss/
    ↳_header.scss
    ↳_footer.scss
    ↳admin.scss
    ↳styles.scss
```
So I use `gulp-sass` to handle the scss files, and then use `gulp-newer` to check if the corresponding file is newer. However, it always comes back as not newer, and the file's aren't changed.

```node
gulp.task('styles', function() {
    return gulp.src('src/scss/*.scss')
        .pipe(plumber())
        .pipe(sourcemaps.init({loadMaps: true}))
            .pipe(sass())
            .pipe(filelog())
            .pipe(newer('css'))
            .pipe(gulp.dest('css'))
            .pipe(prefix("last 1 version", "> 1%", "ie 8"))
            .pipe(minify())
            .pipe(rename({suffix: '.min'}))
        .pipe(sourcemaps.write('.'))
        .pipe(gulp.dest('css/min'))
        .pipe(browserSync.reload({stream:true, once:true}))
        .pipe(notify({message: "Gulp styles task completed"}));
});
```
Maybe you see something I'm missing? I appreciate your time and the plugin works how I want when I have single files, like JS. Thanks

**Comment by piotrd** [comment]
@KevinBatdorf I'm having the same issues with my project. Maybe it's worth opening a separate task for this?

**Comment by KevinBatdorf** [comment]
This seems like so long ago that i don't even remember this code. but I checked back to what I ended up with and here's what I have. I'm assuming I got it to work...

```javascript
gulp.task('styles', function () {
  return gulp.src(paths.sass)
    .pipe(plumber(function (error) {
      gutil.beep();
      gutil.log(gutil.colors.red(error.message));
      this.emit('end');
    }))
    .pipe(newer(themeDir + '/css/style.min.css'))
    .pipe(sourcemaps.init())
      .pipe(sass({errLogToConsole: true}))
      .pipe(prefix())
      .pipe(minify())
      .pipe(rename(function (path) {
        path.extname = ".min.css";
      }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(themeDir + '/css'))
    .pipe(reload({stream:true, once:true}));
});
```
